// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqzreoyxqppovooqzcpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxenJlb3l4cXBwb3Zvb3F6Y3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDU2OTUsImV4cCI6MjA3MjYyMTY5NX0.aEAM8Of-o_TuoEGn6oXayJHdtriqpGBtQ9Zzoo_u2pY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});